import 'chef_rules.dart';

enum ChefTitleStyle { anchorWithSecondary, anchorWithFocus, inventoryLead }

enum ChefStepStyle {
  eggSkillet,
  potatoSkillet,
  freshSalad,
  grainPan,
  pastaPan,
  soup,
  bake,
  breakfast,
  syrniki,
  draniki,
  porridge,
  cutlets,
  stew,
}

class ChefSlot {
  final String key;
  final List<String> candidates;
  final int minCount;
  final int maxCount;
  final bool isAnchor;

  const ChefSlot({
    required this.key,
    required this.candidates,
    required this.minCount,
    required this.maxCount,
    this.isAnchor = false,
  });
}

class ChefBlueprint {
  final String id;
  final DishProfile profile;
  final String titlePrefix;
  final String description;
  final int timeMin;
  final int servingsBase;
  final List<String> tags;
  final String anchorSlot;
  final String? secondaryAnchorSlot;
  final String? supportSlot;
  final List<String> preferredStarters;
  final int maxImplicitPantryStarters;
  final ChefTitleStyle titleStyle;
  final ChefStepStyle stepStyle;
  final List<ChefSlot> slots;

  const ChefBlueprint({
    required this.id,
    required this.profile,
    required this.titlePrefix,
    required this.description,
    required this.timeMin,
    required this.servingsBase,
    required this.tags,
    required this.anchorSlot,
    this.secondaryAnchorSlot,
    this.supportSlot,
    required this.preferredStarters,
    this.maxImplicitPantryStarters = 2,
    required this.titleStyle,
    required this.stepStyle,
    required this.slots,
  });
}

const chefBlueprints = <ChefBlueprint>[
  ChefBlueprint(
    id: 'egg_skillet',
    profile: DishProfile.skillet,
    titlePrefix: 'Яичная сковорода',
    description:
        'Быстрое блюдо на одной сковороде, которое помогает пустить в дело яйца и удачные домашние добавки.',
    timeMin: 12,
    servingsBase: 2,
    tags: ['quick', 'breakfast', 'one_pan', 'no_oven', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'addons',
    preferredStarters: ['соль', 'перец', 'масло', 'паприка'],
    titleStyle: ChefTitleStyle.anchorWithSecondary,
    stepStyle: ChefStepStyle.eggSkillet,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['яйцо'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'addons',
        candidates: [
          'помидор',
          'сыр',
          'лук',
          'перец сладкий',
          'грибы',
          'кабачок',
          'брокколи',
        ],
        minCount: 1,
        maxCount: 2,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'potato_skillet',
    profile: DishProfile.skillet,
    titlePrefix: 'Румяный картофель',
    description:
        'Домашняя сковорода, которая хорошо собирает скоропортящиеся продукты в один сытный ужин.',
    timeMin: 24,
    servingsBase: 2,
    tags: ['one_pan', 'no_oven', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'addons',
    preferredStarters: ['соль', 'перец', 'масло', 'паприка', 'чеснок'],
    titleStyle: ChefTitleStyle.anchorWithSecondary,
    stepStyle: ChefStepStyle.potatoSkillet,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['картофель'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'addons',
        candidates: [
          'лук',
          'грибы',
          'сыр',
          'сметана',
          'сосиски',
          'фарш',
          'курица',
          'перец сладкий',
        ],
        minCount: 1,
        maxCount: 2,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'fresh_salad',
    profile: DishProfile.salad,
    titlePrefix: 'Салат из того, что есть',
    description:
        'Свежий вариант, когда нужно быстро собрать полноценное блюдо без долгой готовки.',
    timeMin: 10,
    servingsBase: 2,
    tags: ['quick', 'light', 'no_oven', 'generated_local'],
    anchorSlot: 'fresh',
    secondaryAnchorSlot: 'protein',
    preferredStarters: [
      'соль',
      'перец',
      'оливковое масло',
      'сметана',
      'йогурт',
      'укроп',
    ],
    titleStyle: ChefTitleStyle.inventoryLead,
    stepStyle: ChefStepStyle.freshSalad,
    slots: [
      ChefSlot(
        key: 'fresh',
        candidates: ['огурец', 'помидор', 'капуста', 'перец сладкий'],
        minCount: 2,
        maxCount: 3,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'protein',
        candidates: ['яйцо', 'тунец', 'сыр', 'фасоль', 'кукуруза', 'творог'],
        minCount: 1,
        maxCount: 2,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'olivier',
    profile: DishProfile.salad,
    titlePrefix: 'Оливье по-домашнему',
    description:
        'Русский салатный формат, который собирает картофель, яйца и праздничные добавки в знакомый домашний вкус.',
    timeMin: 18,
    servingsBase: 3,
    tags: ['salad', 'russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'addons',
    preferredStarters: ['соль', 'перец', 'майонез'],
    maxImplicitPantryStarters: 3,
    titleStyle: ChefTitleStyle.inventoryLead,
    stepStyle: ChefStepStyle.freshSalad,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['картофель', 'яйцо', 'морковь'],
        minCount: 2,
        maxCount: 3,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'addons',
        candidates: ['огурец', 'горошек', 'колбаса'],
        minCount: 2,
        maxCount: 3,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'vinegret',
    profile: DishProfile.salad,
    titlePrefix: 'Винегрет домашний',
    description:
        'Русский корнеплодный салат, который любит свеклу, солёный акцент и спокойную масляную заправку.',
    timeMin: 18,
    servingsBase: 3,
    tags: ['salad', 'russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'addons',
    preferredStarters: ['масло', 'соль', 'перец', 'укроп'],
    maxImplicitPantryStarters: 4,
    titleStyle: ChefTitleStyle.inventoryLead,
    stepStyle: ChefStepStyle.freshSalad,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['свекла', 'картофель', 'морковь'],
        minCount: 2,
        maxCount: 3,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'addons',
        candidates: ['огурец', 'горошек', 'капуста'],
        minCount: 2,
        maxCount: 3,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'grain_pan',
    profile: DishProfile.grainBowl,
    titlePrefix: 'Сытная миска',
    description:
        'Тёплое блюдо, которое использует крупу как основу и собирает вокруг неё самые удачные домашние добавки.',
    timeMin: 22,
    servingsBase: 2,
    tags: ['one_pan', 'generated_local'],
    anchorSlot: 'grain',
    secondaryAnchorSlot: 'protein',
    supportSlot: 'veg',
    preferredStarters: ['соль', 'перец', 'масло', 'паприка', 'чеснок'],
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.grainPan,
    slots: [
      ChefSlot(
        key: 'grain',
        candidates: ['рис', 'гречка', 'кускус'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'protein',
        candidates: ['курица', 'тунец', 'яйцо', 'фасоль', 'чечевица', 'сыр'],
        minCount: 1,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: [
          'морковь',
          'лук',
          'грибы',
          'перец сладкий',
          'помидор',
          'брокколи',
          'кабачок',
        ],
        minCount: 1,
        maxCount: 2,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'grechka_rustic',
    profile: DishProfile.grainBowl,
    titlePrefix: 'Гречка по-домашнему',
    description:
        'Русская сытная гречка, которая лучше всего работает с грибами, луком и простой домашней заправкой.',
    timeMin: 24,
    servingsBase: 2,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'grain',
    secondaryAnchorSlot: 'addons',
    supportSlot: 'veg',
    preferredStarters: ['соль', 'перец', 'масло', 'укроп'],
    maxImplicitPantryStarters: 3,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.grainPan,
    slots: [
      ChefSlot(
        key: 'grain',
        candidates: ['гречка'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'addons',
        candidates: ['грибы', 'курица', 'сосиски', 'говядина'],
        minCount: 1,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['лук', 'морковь'],
        minCount: 1,
        maxCount: 2,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'pasta_pan',
    profile: DishProfile.pasta,
    titlePrefix: 'Макароны на скорую руку',
    description:
        'Быстрое тёплое блюдо, которое хорошо работает, если дома есть паста и пара ярких добавок.',
    timeMin: 18,
    servingsBase: 2,
    tags: ['quick', 'one_pan', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'addons',
    preferredStarters: ['соль', 'перец', 'масло', 'чеснок'],
    titleStyle: ChefTitleStyle.anchorWithSecondary,
    stepStyle: ChefStepStyle.pastaPan,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['макароны'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'addons',
        candidates: [
          'сыр',
          'помидор',
          'тунец',
          'курица',
          'грибы',
          'чеснок',
          'брокколи',
          'томатная паста',
        ],
        minCount: 2,
        maxCount: 3,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'shchi',
    profile: DishProfile.soup,
    titlePrefix: 'Щи домашние',
    description:
        'Капустный суп в русском домашнем стиле, который любит простую овощную базу, лавровый лист и ложку сметаны.',
    timeMin: 38,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'protein',
    supportSlot: 'veg',
    preferredStarters: ['соль', 'перец', 'лавровый лист', 'укроп', 'сметана'],
    maxImplicitPantryStarters: 3,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.soup,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['капуста'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'protein',
        candidates: ['курица', 'говядина'],
        minCount: 0,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['картофель', 'морковь', 'лук'],
        minCount: 2,
        maxCount: 3,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'borscht',
    profile: DishProfile.soup,
    titlePrefix: 'Борщ по-домашнему',
    description:
        'Русско-восточноевропейский свекольный суп, который лучше всего раскрывается на капусте, корнеплодах и мягкой кислой подаче.',
    timeMin: 42,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'protein',
    supportSlot: 'veg',
    preferredStarters: [
      'соль',
      'перец',
      'лавровый лист',
      'укроп',
      'сметана',
      'томатная паста',
    ],
    maxImplicitPantryStarters: 3,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.soup,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['свекла'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'protein',
        candidates: ['говядина', 'курица', 'фасоль'],
        minCount: 0,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: [
          'капуста',
          'картофель',
          'морковь',
          'лук',
          'томатная паста'
        ],
        minCount: 3,
        maxCount: 5,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'ukha',
    profile: DishProfile.soup,
    titlePrefix: 'Уха домашняя',
    description:
        'Русский рыбный суп, который опирается на чистый вкус рыбы, корнеплоды и свежий укропный финиш.',
    timeMin: 34,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'veg',
    preferredStarters: ['соль', 'перец', 'лавровый лист', 'укроп', 'лимон'],
    maxImplicitPantryStarters: 4,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.soup,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['рыба'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['картофель', 'лук', 'морковь'],
        minCount: 2,
        maxCount: 3,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'rassolnik',
    profile: DishProfile.soup,
    titlePrefix: 'Рассольник домашний',
    description:
        'Русский суп с перловкой и солёным огурцом, который любит спокойную овощную базу и мягкий сметанный финиш.',
    timeMin: 40,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'pickles',
    supportSlot: 'veg',
    preferredStarters: ['соль', 'перец', 'лавровый лист', 'сметана'],
    maxImplicitPantryStarters: 4,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.soup,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['перловка'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'pickles',
        candidates: ['огурец'],
        minCount: 1,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['картофель', 'морковь', 'лук'],
        minCount: 2,
        maxCount: 3,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'solyanka',
    profile: DishProfile.soup,
    titlePrefix: 'Солянка домашняя',
    description:
        'Русский наваристый суп, где колбасный акцент, солёный огурец и томатная глубина собираются в яркую домашнюю тарелку.',
    timeMin: 36,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'protein',
    secondaryAnchorSlot: 'sour',
    supportSlot: 'veg',
    preferredStarters: ['соль', 'перец', 'лавровый лист', 'сметана', 'лимон'],
    maxImplicitPantryStarters: 4,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.soup,
    slots: [
      ChefSlot(
        key: 'protein',
        candidates: ['колбаса', 'сосиски', 'говядина'],
        minCount: 1,
        maxCount: 2,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'sour',
        candidates: ['огурец', 'оливки'],
        minCount: 1,
        maxCount: 2,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['лук', 'томатная паста', 'лимон'],
        minCount: 2,
        maxCount: 3,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'home_soup',
    profile: DishProfile.soup,
    titlePrefix: 'Домашний суп',
    description:
        'Спокойный суп из текущих запасов, который помогает собрать овощи и базовые продукты в понятную домашнюю тарелку.',
    timeMin: 30,
    servingsBase: 3,
    tags: ['generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'veg',
    supportSlot: 'extra',
    preferredStarters: [
      'соль',
      'перец',
      'масло',
      'чеснок',
      'лавровый лист',
      'укроп'
    ],
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.soup,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['курица', 'рыба', 'чечевица', 'картофель'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'veg',
        candidates: [
          'морковь',
          'лук',
          'картофель',
          'помидор',
          'капуста',
          'брокколи',
          'кабачок',
          'перец сладкий',
        ],
        minCount: 2,
        maxCount: 3,
      ),
      ChefSlot(
        key: 'extra',
        candidates: ['рис', 'гречка', 'чечевица', 'фасоль'],
        minCount: 0,
        maxCount: 1,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'bake',
    profile: DishProfile.bake,
    titlePrefix: 'Запеканка',
    description:
        'Запечённый вариант для тех случаев, когда хочется собрать холодильник в одно более насыщенное блюдо.',
    timeMin: 34,
    servingsBase: 3,
    tags: ['oven', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'addons',
    supportSlot: 'binder',
    preferredStarters: ['соль', 'перец', 'масло', 'паприка', 'чеснок'],
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.bake,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['курица', 'картофель', 'кабачок', 'брокколи', 'фарш'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'addons',
        candidates: [
          'сыр',
          'сметана',
          'лук',
          'помидор',
          'перец сладкий',
          'грибы'
        ],
        minCount: 2,
        maxCount: 3,
      ),
      ChefSlot(
        key: 'binder',
        candidates: ['яйцо', 'сыр', 'сметана'],
        minCount: 0,
        maxCount: 1,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'millet_kasha',
    profile: DishProfile.breakfast,
    titlePrefix: 'Пшённая каша',
    description:
        'Домашняя сладкая каша на молоке, где пшено собирается с маслом и мягким сладким финишем.',
    timeMin: 22,
    servingsBase: 2,
    tags: ['breakfast', 'russian_classic', 'generated_local'],
    anchorSlot: 'grain',
    secondaryAnchorSlot: 'creamy',
    supportSlot: 'addons',
    preferredStarters: ['сахар', 'корица'],
    maxImplicitPantryStarters: 2,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.porridge,
    slots: [
      ChefSlot(
        key: 'grain',
        candidates: ['пшено'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'creamy',
        candidates: ['молоко', 'масло сливочное', 'сахар'],
        minCount: 2,
        maxCount: 3,
      ),
      ChefSlot(
        key: 'addons',
        candidates: ['яблоко', 'банан', 'корица'],
        minCount: 0,
        maxCount: 1,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'rice_kasha',
    profile: DishProfile.breakfast,
    titlePrefix: 'Рисовая каша',
    description:
        'Спокойная молочная каша по-домашнему, где рис держит мягкую текстуру и любит сливочный финиш.',
    timeMin: 24,
    servingsBase: 2,
    tags: ['breakfast', 'russian_classic', 'generated_local'],
    anchorSlot: 'grain',
    secondaryAnchorSlot: 'creamy',
    supportSlot: 'addons',
    preferredStarters: ['сахар', 'корица'],
    maxImplicitPantryStarters: 2,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.porridge,
    slots: [
      ChefSlot(
        key: 'grain',
        candidates: ['рис'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'creamy',
        candidates: ['молоко', 'масло сливочное', 'сахар'],
        minCount: 2,
        maxCount: 3,
      ),
      ChefSlot(
        key: 'addons',
        candidates: ['яблоко', 'банан', 'корица'],
        minCount: 0,
        maxCount: 1,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'manna_kasha',
    profile: DishProfile.breakfast,
    titlePrefix: 'Манная каша',
    description:
        'Классическая домашняя манка, которая держится на молоке, сливочном масле и мягкой сладкой подаче.',
    timeMin: 12,
    servingsBase: 2,
    tags: ['breakfast', 'russian_classic', 'generated_local'],
    anchorSlot: 'grain',
    secondaryAnchorSlot: 'creamy',
    supportSlot: 'addons',
    preferredStarters: ['сахар', 'корица'],
    maxImplicitPantryStarters: 2,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.porridge,
    slots: [
      ChefSlot(
        key: 'grain',
        candidates: ['манная крупа'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'creamy',
        candidates: ['молоко', 'масло сливочное', 'сахар'],
        minCount: 2,
        maxCount: 3,
      ),
      ChefSlot(
        key: 'addons',
        candidates: ['яблоко', 'банан', 'корица'],
        minCount: 0,
        maxCount: 1,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'breakfast',
    profile: DishProfile.breakfast,
    titlePrefix: 'Домашний завтрак',
    description:
        'Мягкий формат завтрака, который собирается из творога или хлопьев с тем, что уже есть дома.',
    timeMin: 15,
    servingsBase: 2,
    tags: ['quick', 'breakfast', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'addons',
    preferredStarters: ['сахар', 'корица'],
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.breakfast,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['творог', 'овсяные хлопья'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'addons',
        candidates: [
          'яблоко',
          'банан',
          'корица',
          'молоко',
          'йогурт',
          'сметана',
          'апельсин',
        ],
        minCount: 1,
        maxCount: 3,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'syrniki',
    profile: DishProfile.breakfast,
    titlePrefix: 'Сырники',
    description:
        'Русский творожный завтрак, который собирается вокруг творога, яйца и мягкого сладкого финиша.',
    timeMin: 18,
    servingsBase: 2,
    tags: ['quick', 'breakfast', 'russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'binder',
    supportSlot: 'addons',
    preferredStarters: ['сахар', 'сметана', 'корица'],
    maxImplicitPantryStarters: 3,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.syrniki,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['творог'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'binder',
        candidates: ['яйцо'],
        minCount: 1,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'addons',
        candidates: ['яблоко', 'банан', 'корица'],
        minCount: 0,
        maxCount: 1,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'draniki',
    profile: DishProfile.skillet,
    titlePrefix: 'Драники',
    description:
        'Русско-белорусская картофельная сковорода, где тёртый картофель собирается с луком и мягким домашним финишем.',
    timeMin: 20,
    servingsBase: 2,
    tags: ['quick', 'russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'binder',
    supportSlot: 'aromatics',
    preferredStarters: ['соль', 'перец', 'сметана', 'масло'],
    maxImplicitPantryStarters: 4,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.draniki,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['картофель'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'binder',
        candidates: ['яйцо', 'мука'],
        minCount: 1,
        maxCount: 2,
      ),
      ChefSlot(
        key: 'aromatics',
        candidates: ['лук'],
        minCount: 1,
        maxCount: 1,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'lazy_cabbage_rolls',
    profile: DishProfile.stew,
    titlePrefix: 'Ленивые голубцы',
    description:
        'Домашнее тушёное блюдо, где капуста, фарш и рис собираются в спокойный томатный вкус без лишней возни.',
    timeMin: 34,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'protein',
    secondaryAnchorSlot: 'grain',
    supportSlot: 'veg',
    preferredStarters: [
      'соль',
      'перец',
      'томатная паста',
      'сметана',
      'лавровый лист',
    ],
    maxImplicitPantryStarters: 4,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.stew,
    slots: [
      ChefSlot(
        key: 'protein',
        candidates: ['фарш'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'grain',
        candidates: ['рис'],
        minCount: 1,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['капуста', 'лук', 'морковь', 'томатная паста'],
        minCount: 3,
        maxCount: 4,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'kotlet_dinner',
    profile: DishProfile.stew,
    titlePrefix: 'Котлеты по-домашнему',
    description:
        'Домашний котлетный ужин, где мясная основа идёт вместе с простым гарниром и спокойной овощной поджаркой.',
    timeMin: 30,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'protein',
    secondaryAnchorSlot: 'side',
    supportSlot: 'veg',
    preferredStarters: ['соль', 'перец', 'масло', 'сметана'],
    maxImplicitPantryStarters: 4,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.cutlets,
    slots: [
      ChefSlot(
        key: 'protein',
        candidates: ['фарш'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'side',
        candidates: ['картофель', 'гречка', 'рис'],
        minCount: 1,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['лук', 'морковь'],
        minCount: 1,
        maxCount: 2,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'stew',
    profile: DishProfile.stew,
    titlePrefix: 'Домашнее рагу',
    description:
        'Густое блюдо для тех случаев, когда хочется использовать основу и овощи без лишней сложности.',
    timeMin: 32,
    servingsBase: 3,
    tags: ['generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'veg',
    supportSlot: 'extra',
    preferredStarters: [
      'соль',
      'перец',
      'масло',
      'паприка',
      'чеснок',
      'томатная паста'
    ],
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.stew,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['чечевица', 'фасоль', 'картофель', 'фарш'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'veg',
        candidates: [
          'лук',
          'морковь',
          'помидор',
          'капуста',
          'перец сладкий',
          'чеснок',
          'кабачок',
        ],
        minCount: 2,
        maxCount: 3,
      ),
      ChefSlot(
        key: 'extra',
        candidates: ['курица', 'рис', 'грибы'],
        minCount: 0,
        maxCount: 1,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'zharkoe',
    profile: DishProfile.stew,
    titlePrefix: 'Жаркое по-домашнему',
    description:
        'Классическое русское жаркое, где картофель собирает мясо, корнеплоды и спокойный густой соус.',
    timeMin: 36,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'protein',
    supportSlot: 'veg',
    preferredStarters: ['соль', 'перец', 'лавровый лист', 'чеснок', 'сметана'],
    maxImplicitPantryStarters: 3,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.stew,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['картофель'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'protein',
        candidates: ['говядина', 'свинина', 'курица'],
        minCount: 1,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['лук', 'морковь', 'грибы', 'перец сладкий'],
        minCount: 1,
        maxCount: 2,
      ),
    ],
  ),
  ChefBlueprint(
    id: 'stewed_cabbage',
    profile: DishProfile.stew,
    titlePrefix: 'Тушёная капуста',
    description:
        'Домашняя тушёная капуста, которая любит лук, морковь, томатную глубину и при желании колбасный акцент.',
    timeMin: 28,
    servingsBase: 3,
    tags: ['russian_classic', 'generated_local'],
    anchorSlot: 'base',
    secondaryAnchorSlot: 'protein',
    supportSlot: 'veg',
    preferredStarters: [
      'соль',
      'перец',
      'лавровый лист',
      'томатная паста',
    ],
    maxImplicitPantryStarters: 4,
    titleStyle: ChefTitleStyle.anchorWithFocus,
    stepStyle: ChefStepStyle.stew,
    slots: [
      ChefSlot(
        key: 'base',
        candidates: ['капуста'],
        minCount: 1,
        maxCount: 1,
        isAnchor: true,
      ),
      ChefSlot(
        key: 'protein',
        candidates: ['колбаса', 'сосиски', 'курица', 'свинина'],
        minCount: 0,
        maxCount: 1,
      ),
      ChefSlot(
        key: 'veg',
        candidates: ['лук', 'морковь', 'томатная паста'],
        minCount: 2,
        maxCount: 3,
      ),
    ],
  ),
];
